### ISSUE TITLE
Some countries don't link to their respective gdrive directories

### ISSUE THREAD

**Issue by brew** [okfn/ibp-explorer#114]
This is the case where the country name on the website differs to that used as the directory name in gdrive:

Website | GDrive
--- | ------
São Tomé e Príncipe | Sao Tome e Principe
Moldova, Republic of | Moldova
Dem. Rep. of Congo | Democratic Republic of Congo
Côte d’Ivoire | Cote d'Ivoire
Russia | Russian Federation
South Korea | South Korea*
Yemen | Yemen*

*Included in the country override here: https://github.com/okfn/ibp-explorer/blob/09d14efbfd117b3870d5e1a10782e73220620a3c/routes/index.js#L48-L51

**Comment by brew** [comment]
Changing the gdrive names to reflect those used on the website will allow them to be matched correctly. In the case of those being overridden (South Korea and Yemen), the gdrive name should be that pre-override, namely "Korea, Republic of" and "Yemen, Rep.".

**Comment by pwalsh** [comment]
Assume changes done on side of the client.
