### ISSUE TITLE
GDrive directory linking issues

### ISSUE THREAD

**Issue by brew** [okfn/ibp-explorer#115]
While working with the [directory naming conventions](https://docs.google.com/document/d/12MyIFKF0rI5dlXB5p1VplEoY0q59ZB8PbxTrqNXaXa0/edit?ts=5811da75) document, there are some issues to look out for when creating Google Drive directories that might prevent linking within the Tracker:

**Whitespace**: A double-whitespace between words is hard to notice, especially because Google Drive is a web application, and html usually collapses extra whitespace. E.g.: [Argentina](https://drive.google.com/drive/folders/0ByA9wmvBrAnZQjRyRkVrWEprUEU)/Executive's Budget Proposal contains a double-whitespace between 'Executive's' and 'Budget'.

**Hyphens**: Ensure that report names contain the correct hyphenation. E.g. [Albania]( https://drive.google.com/drive/folders/0ByA9wmvBrAnZYUxua0tQWVo3bGc)/Year End Report should be hyphenated: Year-End.

**Comment by pwalsh** [comment]
Assume fixed by client.
