### ISSUE TITLE
Text change on columns based on document state

### ISSUE THREAD

**Issue by pwalsh** [okfn/ibp-explorer#79]
# Client requests
- Is it possible to change the text in the “Date of Publication” column if the document is Not Produced or Internal Use Only? Currently it says “Unavailable,” but we might want to change that to something else.
# Actions
- As long as this is data we can get from the API, yes. Can you point out how we "know" this from the API?
- Blocked until we know if the API provides information to do this. David is checking

**Comment by pwalsh** [comment]
@dumyan is this possible for you to work out, or do we need more info still?

**Comment by dumyan** [comment]
@pwalsh I don't think we have any input about what should the text be instead of 'Unavailable'. Am I wrong? 

As of being doable - yes, this is minor modification, it can be done with modifying the template.

**Comment by dumyan** [comment]
David requested that we use `-` instead of Unavailable. DONE
